// Create web server
// npm install express
// npm install body-parser
// npm install mongoose
// npm install method-override
// npm install express-sanitizer
// npm install ejs
// npm install passport
// npm install passport-local
// npm install passport-local-mongoose
// npm install express-session
// npm install connect-flash